### ISSUE TITLE
Support 1.14.4

### ISSUE THREAD

**Issue by MisterRickiy** [liachmodded/runorama#1]
[crash-2019-09-05_20.42.42-client.txt](https://github.com/liachmodded/runorama/files/3580763/crash-2019-09-05_20.42.42-client.txt)

**Comment by liach** [comment]
Fyi 1.14.4 is not yet supported by this mod. Will release a 1.14.4 version soon :tm:

**Comment by liach** [comment]
Code is done, but I have trouble logging into twitch so you need to wait a bit unfortunately

**Comment by liach** [comment]
A 1.14.4 version is available on curseforge now. https://www.curseforge.com/minecraft/mc-mods/runorama/files/2791273
