### ISSUE TITLE
Optifabric mixin crash

### ISSUE THREAD

**Issue by xAlicatt** [liachmodded/runorama#3]
Works with Runorama disabled. Using Fabric API 0.3.3 build 234 and Loader 0.6.1 build 165

[Report](https://paste.dimdev.org/ihiwuqunib.sql)

**Comment by liach** [comment]
Hmm, I guess this may be related to optifabric. Let me test again

**Comment by liach** [comment]
https://discordapp.com/channels/142425412096491520/142425521391665153/626547197248405534
According to mumfrey, this will be fixed once fabric loader starts to use mixin 0.8.

**Comment by liach** [comment]
Fixed in 057ec7d. Thanks!
